### ISSUE TITLE
存储桶设置

### ISSUE THREAD

**Issue by GeekF0rum** [znc15/wordpress-lskypro#1]
请问后面会添加存储ID的绑定吗，就是上传到对应的存储。

**Comment by GeekF0rum** [comment]
图片直接在媒体库上传吗？我在使用中上传了但是并没有获取到图床url呢，这是为什么？

**Comment by znc15** [comment]
> 图片直接在媒体库上传吗？我在使用中上传了但是并没有获取到图床url呢，这是为什么？

更新最新版本，修好了（本地测试明明没有问题的

**Comment by znc15** [comment]
已经加入
